"""content models, profile fields, db-backed auth

Revision ID: 3c5ca66e196c
Revises: 758cc69959ee
Create Date: 2026-07-16 10:36:25.864011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5ca66e196c'
down_revision: Union[str, None] = '758cc69959ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_company_org_name')
    )
    op.create_index(op.f('ix_companies_organization_id'), 'companies', ['organization_id'], unique=False)
    op.create_table('industries',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_industry_org_name')
    )
    op.create_index(op.f('ix_industries_organization_id'), 'industries', ['organization_id'], unique=False)
    op.create_table('universities',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_university_org_name')
    )
    op.create_index(op.f('ix_universities_organization_id'), 'universities', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_imports',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('row_errors_json', sa.Text(), nullable=True),
    sa.Column('imported_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_imports_organization_id'), 'csv_imports', ['organization_id'], unique=False)
    op.create_table('events',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('virtual_url', sa.String(length=512), nullable=True),
    sa.Column('registration_url', sa.String(length=512), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_table('legal_name_change_requests',
    sa.Column('alumni_id', sa.String(length=36), nullable=False),
    sa.Column('requested_legal_name', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['alumni_id'], ['alumni.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_name_change_requests_alumni_id'), 'legal_name_change_requests', ['alumni_id'], unique=False)
    op.create_table('speakers',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=4000), nullable=True),
    sa.Column('profile_image_url', sa.String(length=512), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('speaking_topics', sa.String(length=1000), nullable=True),
    sa.Column('availability_status', sa.String(length=64), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_organization_id'), 'speakers', ['organization_id'], unique=False)
    op.create_table('super_stars',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('alumni_id', sa.String(length=36), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('featured_image_url', sa.String(length=512), nullable=True),
    sa.Column('featured_at', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alumni_id'], ['alumni.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_stars_alumni_id'), 'super_stars', ['alumni_id'], unique=False)
    op.create_index(op.f('ix_super_stars_organization_id'), 'super_stars', ['organization_id'], unique=False)
    op.drop_table('user_organization_roles')
    op.add_column('alumni', sa.Column('preferred_name', sa.String(length=128), nullable=True))
    op.add_column('alumni', sa.Column('verified_legal_name', sa.String(length=256), nullable=True))
    op.add_column('alumni', sa.Column('legal_name_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column(
        'alumni',
        sa.Column('legal_name_verification_status', sa.String(length=32), nullable=False, server_default='unverified'),
    )
    op.add_column('alumni', sa.Column('legal_name_verified_at', sa.Date(), nullable=True))
    op.add_column('alumni', sa.Column('graduation_date', sa.Date(), nullable=True))
    op.add_column('alumni', sa.Column('profile_image_url', sa.String(length=512), nullable=True))
    op.add_column('alumni', sa.Column('bio', sa.String(length=4000), nullable=True))
    op.add_column(
        'alumni',
        sa.Column('profile_visibility', sa.String(length=32), nullable=False, server_default='organization'),
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=False, server_default='alumni'))
        batch_op.add_column(sa.Column('alumni_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_users_alumni_id', ['alumni_id'])
        batch_op.create_foreign_key('fk_users_alumni_id', 'alumni', ['alumni_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_alumni_id', type_='foreignkey')
        batch_op.drop_constraint('uq_users_alumni_id', type_='unique')
        batch_op.drop_column('alumni_id')
        batch_op.drop_column('role')
    op.drop_column('alumni', 'profile_visibility')
    op.drop_column('alumni', 'bio')
    op.drop_column('alumni', 'profile_image_url')
    op.drop_column('alumni', 'graduation_date')
    op.drop_column('alumni', 'legal_name_verified_at')
    op.drop_column('alumni', 'legal_name_verification_status')
    op.drop_column('alumni', 'legal_name_verified')
    op.drop_column('alumni', 'verified_legal_name')
    op.drop_column('alumni', 'preferred_name')
    op.create_table('user_organization_roles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization')
    )
    op.drop_index(op.f('ix_super_stars_organization_id'), table_name='super_stars')
    op.drop_index(op.f('ix_super_stars_alumni_id'), table_name='super_stars')
    op.drop_table('super_stars')
    op.drop_index(op.f('ix_speakers_organization_id'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_legal_name_change_requests_alumni_id'), table_name='legal_name_change_requests')
    op.drop_table('legal_name_change_requests')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_csv_imports_organization_id'), table_name='csv_imports')
    op.drop_table('csv_imports')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_universities_organization_id'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_industries_organization_id'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_companies_organization_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
