"""initial schema

Revision ID: 758cc69959ee
Revises: 
Create Date: 2026-07-14 22:15:30.683606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758cc69959ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('career_category', sa.String(length=255), nullable=True),
    sa.Column('seniority', sa.String(length=64), nullable=True),
    sa.Column('industry_source', sa.String(length=32), nullable=False),
    sa.Column('career_category_source', sa.String(length=32), nullable=False),
    sa.Column('seniority_source', sa.String(length=32), nullable=False),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('profile_completion', sa.Integer(), nullable=False),
    sa.Column('location_original', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('state_code', sa.String(length=8), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('metro_area', sa.String(length=128), nullable=True),
    sa.Column('display_location', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_normalization_status', sa.String(length=32), nullable=False),
    sa.Column('location_normalized_at', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_city'), 'alumni', ['city'], unique=False)
    op.create_index(op.f('ix_alumni_linkedin_url'), 'alumni', ['linkedin_url'], unique=False)
    op.create_index(op.f('ix_alumni_metro_area'), 'alumni', ['metro_area'], unique=False)
    op.create_index(op.f('ix_alumni_state'), 'alumni', ['state'], unique=False)
    op.create_table('location_aliases',
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('canonical_city', sa.String(length=128), nullable=True),
    sa.Column('canonical_state', sa.String(length=64), nullable=True),
    sa.Column('state_code', sa.String(length=8), nullable=True),
    sa.Column('canonical_country', sa.String(length=128), nullable=True),
    sa.Column('metro_area', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_aliases_alias'), 'location_aliases', ['alias'], unique=True)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alumni_organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alumni_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alumni_id'], ['alumni.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumni_id', 'organization_id', name='uq_alumni_organization')
    )
    op.create_table('user_organization_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_organization_roles')
    op.drop_table('alumni_organizations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_location_aliases_alias'), table_name='location_aliases')
    op.drop_table('location_aliases')
    op.drop_index(op.f('ix_alumni_state'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_metro_area'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_linkedin_url'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_city'), table_name='alumni')
    op.drop_table('alumni')
    # ### end Alembic commands ###
